export const OCCUPY_SEATS = 'OCCUPY_SEATS';
export const SELECT_SEAT = 'SELECT_SEAT';
export const DESELECT_SEAT = 'DESELECT_SEAT';
export const CLEAR_SELECTION = 'CLEAR_SELECTION';

export const SET_MESSAGE_VISIBLE = 'SET_MESSAGE_VISIBLE';
